# Dependabot version updates
# https://docs.github.com/es/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configuring-dependabot-version-updates

version: 2
updates:
  # PHP (Composer / Laravel)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # JavaScript (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
